version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:2.232
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/atishukla/.docker:/root/.docker
      - /etc/localtime:/etc/localtime:ro
  
  nexus:
    image: sonatype/nexus3
    privileged: true
    user: root
    ports:
      - 18081:8081
    # container_name: nexus
    volumes:
      - nexus-dv:/nexus-data

volumes:
  # jenkins-dv:
  #   driver: local
  nexus-dv:
    driver: local