version: '3.7'
services:
  jenkins:
    image: jenkins:2.60.3
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-dv:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  
  nexus:
    image: sonatype/nexus3
    privileged: true
    user: root
    ports:
      - 18081:8081
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data

volumes:
  jenkins-dv:
    driver: local
  nexus-dv:
    driver: local